{
  "Formación académica y complementaria": [
    "FORMACIÓN ACADÉMICA",
    "FORMACION ACADEMICA",
    "FORMACIÓN ACADÉMICA Y COMPLEMENTARIA",
    "FORMACION ACADEMICA Y COMPLEMENTARIA"
  ],
  "Producción científica": [
    "PUBLICACIONES",
    "PRODUCCIÓN CIENTÍFICA",
    "PRODUCCION CIENTIFICA"
  ],
  "Formación de Recursos Humanos": [
    "FORMACIÓN DE RECURSOS HUMANOS",
    "FORMACION DE RECURSOS HUMANOS",
    "RECURSOS HUMANOS",
    "RRHH"
  ],
  "Investigación científica y tecnológica": [
    "ANTECEDENTES EN CIENCIA Y TECNOLOGÍA",
    "ANTECEDENTES EN CIENCIA Y TECNOLOGIA",
    "INVESTIGACIÓN CIENTÍFICA Y TECNOLÓGICA",
    "INVESTIGACION CIENTIFICA Y TECNOLOGICA"
  ],
  "Financiamiento CyT": [
    "FINANCIAMIENTO",
    "PROYECTOS DE INVESTIGACIÓN",
    "PROYECTOS DE INVESTIGACION"
  ],
  "Actividad científica": [
    "ACTIVIDAD CIENTÍFICA",
    "ACTIVIDAD CIENTIFICA",
    "EVENTOS",
    "PRESENTACIÓN EN REUNIONES CIENTÍFICAS",
    "PRESENTACION EN REUNIONES CIENTIFICAS"
  ],
  "Gestión universitaria": [
    "GESTIÓN UNIVERSITARIA",
    "GESTION UNIVERSITARIA"
  ]
}
